version: "3"
services:

  web:
    container_name: redaxodocker
    hostname: redaxodocker
    build: ./docker/php-apache              # location for web server dockerfile and config
    ports:
      - 20080:80                            # web server will use port 20080 for http
      - 20443:443                           # web server will use port 20443 for https
    volumes:
      - ./html:/var/www/html:cached         # webroot `/var/www/html` will be synced with your local folder `./html`
    depends_on:
      - db
      - mailhog
    links:
      - db
      - mailhog
    environment:
      REDAXO_USER: admin                    # username of your new REDAXO admin
      REDAXO_PASSWORD: admin                # password of your new REDAXO admin
      REDAXO_DEMO: demo_base                # website demo to be installed. leave empty for a raw REDAXO!

  db:
    container_name: redaxodocker_db
    hostname: redaxodocker_db
    build: ./docker/mysql                   # location for database dockerfile and config
    ports:
      - 23306:3306                          # database will use port 23306
    volumes:
      - ./db:/var/lib/mysql:cached          # database in `/var/lib/mysql` will be synced with your local folder `./db`
    environment:
      MYSQL_DATABASE: redaxo
      MYSQL_USER: redaxo
      MYSQL_PASSWORD: redaxo
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  mailhog:
    container_name: redaxodocker_mailhog
    hostname: redaxodocker_mailhog
    build: ./docker/mailhog                 # location for mailhog dockerfile and config
    ports:
      - 28025:8025                          # mailhog will use port 28025 (for its web interface)
      - 1025:1025                           # mailhog will use port 1025 (for smtp)
